### PR TITLE
Adds support for X212-276 Claim Status Request.

### PR DESCRIPTION
**Pull request by RomanKapitonov**
This PR intends to add missing guides from https://github.com/irobayna/stupidedi/issues/137

### CODE REVIEW

**Comment by RomanKapitonov** [comment]
I've amended a new commit since the first one was broken. Confirmed it is working by using bin/edi-pp with the list of 276 fixtures

**Comment by irobayna** [comment]
@RomanKapitonov Fantastic!  Any chance we could also add some specs?

**Comment by RomanKapitonov** [comment]
@irobayna I will return to the specs once I have other duties. I've also fixed the html writer which is currently broken, will create a pull request for that later on. And since we need a json representation of the parsed envelopes it seems like i've been able to generate json document based on the schema. Even though it will not be included in the source is may still be added as an example to the notes. Yet still working on that.

**Comment by RomanKapitonov** [comment]
@irobayna, Please review the changes, I've added integration tests for HR276 and reorganized parsing specs without making changes to them. BTW is there any reason to use `*.example` extension? Why not switch to plain `*.rb` files.

**Comment by irobayna** [comment]
@RomanKapitonov Historically reason, they were created as *.example and we left them that way since.  I would be open to another PR renaming those to *_spec.rb

BTW, thank you for this PR

**Pull request merged**
