### PR TITLE
Throw exception from #iterate if segment is not repeatable (fix #126)

### LINKED ISSUE #126: #Iterate could check that segment shouldn't repeat
There's a small issue that I think enough people have encountered (probably not realizing it), that it would be helpful to beginners if it was fixed: `foo.iterate(:XYZ)` doesn't actually check that `XYZ` is a repeating segment.

If `XYZ` is not repeating (according to the grammar), then in cases where it finds `XYZ` the first time, it will throw an exception at the end of the given block when it tries to do another `find` -- "XYZ cannot be reached from this state". That's a confusing error because it appears that *did* find XYZ!

In the other case is that it didn't find `XYZ`, it doesn't throw an exception that you shouldn't have used `iterate`... it's kind of a bug waiting to happen when you eventually have a file that did have an `XYZ`.

I think we could change the definition of `iterate` by adding a test at the start, before calling `find`. This seems like a small change that would be good for a contributor to work on, and I think there's some code already (somewhere?) that checks if a segment is repeatable and throws an error if it's not... try searching for `repeatable?`. It might be in the Guide Builder code.

### PR DESCRIPTION
**Pull request by kputnam**
This change ensures that whatever parameters are provided to `iterate` refer to a repeatable segment in the document schema. The input doesn't actually need to have a matching segment for the check to happen; thus, a previously latent bug (calling `iterate` when it shouldn't have been called) will now be made more likely to be caught.

```ruby
config = Stupidedi::Config.hipaa
reader = Stupidedi::Reader.build(File.open("spec/fixtures/X222-HC837/1-good.txt"))
parser = Stupidedi::Builder::StateMachine.build(config)

parser, result = parser.read(reader)
parser.first.tap do |isa|
  isa.iterate(:GS) do |gs|
    gs.iterate(:ST) do |st|
      st.iterate(:BHT) do #=> BHT segment is not repeatable (Stupidedi::Exceptions::ParseError)
        ...
      end
    end
  end
end
```

One thing that's not ideal is the error is thrown from `__find`, which the user didn't call themselves. However, the next stack frame is `iterate` and the next one after that is where the user called it from.

### CODE REVIEW

**Comment by irobayna** [comment]
@kputnam Thank you!

**Comment by irobayna** [comment]
@kputnam Some code where I use `iterate` is throwing this exception but the item is supposed to iterate.  What am I missing?

```  
 d::TableDef.detail("Table 2 - Detail",
            d::LoopDef.build("2000 HEADER NUMBER",
              d::RepeatCount.bounded(100),
              b::Segment(30, s::LX, "Header Number",
                r::Situational, d::RepeatCount.bounded(1),
                b::Element(e::Required,    "Assigned Number")), 
```

```ruby
   st.iterate(:LX) do |lx|
...
```

```__find': LX segment is not repeatable (Stupidedi::Exceptions::ParseError)```

**Comment by kputnam** [comment]
Oops, I messed that up... it's obvious to me now 😳. The problem is the test should be looking at `successors` instead of the SegmentUse (by definition the first segment of every loop will have repeat of 1, even though the loop itself can repeat). I should've noticed the logic wasn't correct when I needed a special case for `ISA`, `GS`, and `ST`... those would've been handled without a special case if the logic was correct.

I'll start on the fix, but perhaps you can release a workaround in the meantime, by changing the `assert_repeatable = true` argument to `false` at [line 456](https://github.com/irobayna/stupidedi/blob/20af106affa7ef0b9bd88e0fcf6886ecc67f0ef8/lib/stupidedi/builder/navigation.rb#L456). That will revert the behavior back to how it used to work (where users can call `iterate` even when it shouldn't be allowed), but at least it won't be unusable.

**Comment by irobayna** [comment]
@kputnam The workaround works as expected.

On a side note, I changed the bounded count from `1` to `100` on the example above and started getting this other error which I am not sure is new:

```bash
.../stupidedi/guides/005010/guide_builder.rb:27:in 
`block (2 levels) in build': 2000 HEADER NUMBER is an entry point into Table 2 - Detail.
Both are marked repeatable, but only one should be repeatable to avoid generating an 
ambiguous grammar. 
You probably want to change the repeat count of 
2000 HEADER NUMBER (Stupidedi::Exceptions::InvalidSchemaError)
```

With the workaround I am able to iterate over `LX` (it should) but I am concerned the grammar might be incorrectly defined:

```
 d::TableDef.detail("Table 2 - Detail",
            d::LoopDef.build("2000 HEADER NUMBER",
              d::RepeatCount.bounded(1),
              b::Segment(30, s::LX, "Header Number",
                r::Situational, d::RepeatCount.bounded(1),
                b::Element(e::Required,    "Assigned Number")),
```
 yet if I try `bounded(100)` I get the other errror

**Comment by kputnam** [comment]
Yeah, the error about "both are marked repeatable" is not a new error. It's there because when the parser sees an `LX` segment, it could either create a whole new "Table 2" with a new "Loop 2000" or it could create only a new "Loop 2000" within the current "Table 2".

I believe the parser will always create a new "Table 2", so the error message is to let you know even if you declare the LX loop is repeatable, it won't ever be repeated in the parse tree. Instead, you will have a new "Table 2" with only a single "Loop 2000" loop inside it.

Despite that, as long as you're using `find` and `iterate` and whatnot, your client code won't even notice the difference. The only way you'd notice is if your code explicitly uses tables and loops, by calling `.parent` on a segment or something. You can probably see it in the output of `edi-pp`. But if you're just using `find` and `iterate` to move around, either way of structuring the parse tree will seem equivalent to the client.

**Comment by kputnam** [comment]
@irobayna, I took another look at this and I don't think `TableDef.detail` tables need to be repeatable. It was repeatable by default, and later someone submitted a PR to allow making non-repeatable detail tables with an extra argument. There might be a grammar that only works if the detail table can repeat, so I'll double-check, but I think it was just conservative decision to be most "flexible".

Currently, when the table is repeatable, the parser will prefer to construct an entirely new table rather than another occurrence of a loop within the current table (see `./bin/edi-pp spec/fixtures/X221-HP835/1-good.txt | grep -E '[A-Z].*Val'`).

```
      TransactionSetVal[HP835](
        TableVal[Table 1 - Header](
          SegmentVal[ST: Transaction Set Header](
          ...
          LoopVal[1000A PAYER IDENTIFICATION](
            SegmentVal[N1: Payer Identification](
            ...
          LoopVal[1000B PAYEE IDENTIFICATION](
            SegmentVal[N1: Payee Identification](
            ...
        TableVal[Table 2 - Detail](
          LoopVal[2000 HEADER NUMBER](
            SegmentVal[LX: Header Number](
            ...
            LoopVal[2100 CLAIM PAYMENT INFORMATION](
              SegmentVal[CLP: Claim Payment Information](
              ...
        TableVal[Table 2 - Detail](
          LoopVal[2000 HEADER NUMBER](
            SegmentVal[LX: Header Number](
            ...
            LoopVal[2100 CLAIM PAYMENT INFORMATION](
              SegmentVal[CLP: Claim Payment Information](
              ...
        TableVal[Table 3 - Summary](
          SegmentVal[PLB: Provider Adjustment](
          SegmentVal[SE: Transaction Set Trailer](
```

I'm going to look into changing it so `TableDef.detail` doesn't repeat, because that will simplify a couple things, including making your `TransactionSetDef` match your specification more closely. It also means you will need to make the loop repeatable below a `TableDef`, but I'll include those changes in a PR if I go further.

**Pull request merged**
