### PR TITLE
Adds an example of traversing stupidedi tree to a ruby hash.

### PR DESCRIPTION
**Pull request by RomanKapitonov**

### CODE REVIEW

**Comment by irobayna** [comment]
@RomanKapitonov WOW! I'm speechless, this has been on my todo list for ages.  Code looks great.  Thank you.

**Comment by irobayna** [comment]
@RomanKapitonov Could you add a section to the main README about this new writer?  Not super obvious for people stumbling onto this repo that that feature is now available.

**Comment by irobayna** [comment]
@RomanKapitonov trying to get in touch with you, could you email me?

**Comment by RomanKapitonov** [comment]
@irobayna I've just sent you an email to the address specified in your profile, hope you have received it

**Pull request merged**
